name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI Workloads
      run: dotnet workload restore
    - name: Restore dependencies for Server
      run: dotnet restore AccountingApp.Server/AccountingApp.Server.csproj --framework net8.0
    - name: Restore dependencies for Client
      run: dotnet restore AccountingApp.Client/AccountingApp.Client.csproj --framework net8.0-android
    - name: Restore dependencies for Mobile
      run: dotnet restore AccountingApp.Mobile/AccountingApp.Mobile.csproj --framework net8.0-android
    - name: Build for Android and Desktop
      run: |
        dotnet build AccountingApp.Server/AccountingApp.Server.csproj --framework net8.0 --no-restore
        dotnet build AccountingApp.Client/AccountingApp.Client.csproj --framework net8.0-android --no-restore
        dotnet build AccountingApp.Mobile/AccountingApp.Mobile.csproj --framework net8.0-android --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal