name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI Workloads
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build for Android and Desktop
      run: |
        dotnet build AccountingApp.Server -f net8.0
        dotnet build AccountingApp.Client -f net8.0-android
        dotnet build AccountingApp.Mobile -f net8.0-android
    - name: Test
      run: dotnet test --no-build --verbosity normal