name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI Workloads
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore AccountingApp.sln
    - name: Build Server
      run: dotnet build AccountingApp.Server/AccountingApp.Server.csproj -f net8.0 --no-restore
    - name: Build Client
      run: dotnet build AccountingApp.Client/AccountingApp.Client.csproj -f net8.0-android --no-restore
    - name: Build Mobile
      run: dotnet build AccountingApp.Mobile/AccountingApp.Mobile.csproj -f net8.0-android --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal